### PR TITLE
Feature: Sync fork with upstream script

### PR DESCRIPTION
**Pull request by epwn**
Added a script which will update a git fork with its original source.
Cuts down on reptitive commands when deploying the latest BlueBox Ursula
code.

### CODE REVIEW

**Comment by eggshell** [comment]
change the shebang to `#!/usr/bin/env bash` for portability.

**Comment by davidcusatis** [comment]
this breaks if you have remotes named something other than upstream

**Comment by epwn** [comment]
yes it would, but you could just use a sed command to replace that in the code

**Comment by eggshell** [comment]
Might need to go back to the drawing board on this one.

**Comment by epwn** [comment]
could have the script find the upstream equivalent? or make it dynamic and just add a required argument

**Comment by eggshell** [comment]
Why don't we just hardcode it to look for a remote that points to https://github.com/CullenTaylor/sl-tools.git ?

**Comment by epwn** [comment]
the purpose wasnt to make it repo specific. its so you could update an ursula fork or something similar. but maybe that would work if if we wanted to make it specific to this repo

**Comment by eggshell** [comment]
Ah okay. Well, first of all, why does it break if there are remotes other than upstream? @davidcusatis

**Comment by davidcusatis** [comment]
no, it breaks if the repo i want to sync is not named upstream, for example, my ursula repo upstream is not named upstream. but i guess that's just me lol

**Comment by davidcusatis** [comment]
```
Davids-MacBook-Pro-3:ursula david$ git remote -v
bluebox_ursula  https://github.com/blueboxgroup/ursula.git (fetch)
bluebox_ursula  https://github.com/blueboxgroup/ursula.git (push)
origin  https://github.com/davidcusatis/ursula.git (fetch)
origin  https://github.com/davidcusatis/ursula.git (push)
Davids-MacBook-Pro-3:ursula david$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by epwn** [comment]
@davidcusatis not naming the original repo 'upstream' is bunz bud. ;)

**Comment by eggshell** [comment]
@davidcusatis ah okay. Yeah I always use upstream as the remote for the repo I forked from

**Pull request merged**
